-- ============================================
-- Bulk product import — Pokemon English
-- Source: Google Sheet gid=490656257
-- 147 unique products generated
-- ============================================

INSERT INTO products (brand, type, category, name, language, breakable, packs_per_box) VALUES
('Pokemon', 'Pack', 'Booster Pack', 'Perfect Order Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Bundle', 'Perfect Order Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Ascended Heroes Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Phantasmal Flames Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Bundle', 'Phantasmal Flames Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Mega Evolution Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Mega Evolution Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Bundle', 'Mega Evolution Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'White Flare Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Bundle', 'White Flare Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Black Bolt Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Bundle', 'Black Bolt Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Destined Rivals Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Destined Rivals Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Bundle', 'Destined Rivals Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Journey Together Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Journey Together Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Blister Pack', 'Journey Together 3 Pack Blister', 'EN', true, 3),
('Pokemon', 'Sealed', 'Booster Bundle', 'Journey Together Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Surging Sparks Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Surging Sparks Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Bundle', 'Surging Sparks Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Prismatic Evolutions Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Blister Pack', 'Prismatic Evolutions 2-Pack Blister', 'EN', true, 2),
('Pokemon', 'Sealed', 'Booster Bundle', 'SV Prismatic Evolutions Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Stellar Crown Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Bundle', 'Stellar Crown Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Twilight Masquerade Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Twilight Masquerade Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Paldean Fates Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Bundle', 'Paldean Fates Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Temporal Forces Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Temporal Forces Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Blister Pack', 'Temporal Forces 3 Pack Blister', 'EN', true, 3),
('Pokemon', 'Sealed', 'Booster Bundle', 'Temporal Forces Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Paradox Rift Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Paradox Rift Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Pokemon 151 Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Bundle', 'SV 151 Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Obsidian Flames Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Bundle', 'Obsidian Flames Booster Bundle', 'EN', true, 6),
('Pokemon', 'Sealed', 'Blister Pack', 'Paldea Evolved Blister Pack', 'EN', true, 1),
('Pokemon', 'Pack', 'Booster Pack', 'Crown Zenith Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Bundle', 'Crown Zenith Booster Bundle', 'EN', true, 6),
('Pokemon', 'Pack', 'Booster Pack', 'Lost Origin Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Astral Radiance Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Astral Radiance Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Brilliant Stars Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Blister Pack', 'Brilliant Stars Single Pack Blister', 'EN', true, 1),
('Pokemon', 'Pack', 'Booster Pack', 'Fusion Strike Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Chilling Reign Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Blister Pack', 'Chilling Reign Single Pack Blister', 'EN', true, 1),
('Pokemon', 'Pack', 'Booster Pack', 'Battle Styles Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Vivid Voltage Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Vivid Voltage Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Rebel Clash Sleeved Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Sword & Shield Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Celebrations Booster Pack', 'EN', false, NULL),
('Pokemon', 'Pack', 'Booster Pack', 'Sun & Moon Booster Pack', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Booster Box', 'Perfect Order Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Perfect Order Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Build & Battle', 'Perfect Order Build & Battle Box', 'EN', true, 4),
('Pokemon', 'Sealed', 'Booster Box', 'Phantasmal Flames Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'Build & Battle', 'Phantasmal Flames Build & Battle Box', 'EN', true, 4),
('Pokemon', 'Sealed', 'Booster Box', 'Mega Evolution Enhanced Booster Box', 'EN', true, 14),
('Pokemon', 'Sealed', 'Booster Box', 'Mega Evolution Enhanced Booster Display Box w/ promo', 'EN', true, 18),
('Pokemon', 'Sealed', 'ETB', 'Mega Evolution Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Mega Evolution Pokemon Center Elite Trainer Box [Mega Gardevoir]', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Mega Evolution Pokemon Center Elite Trainer Box [Mega Lucario]', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'White Flare Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Black Bolt Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Destined Rivals Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Destined Rivals Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Journey Together Enhanced Booster Box', 'EN', true, 14),
('Pokemon', 'Sealed', 'ETB', 'Journey Together Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Surging Sparks Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Surging Sparks Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Surging Sparks Pokemon Center Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Prismatic Evolutions Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Stellar Crown Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Shrouded Fable Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Shrouded Fable Pokemon Center Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Twilight Masquerade Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Twilight Masquerade Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Paldean Fates Pokemon Center Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Temporal Forces Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Temporal Forces Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Paradox Rift Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', '151 Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Obsidian Flames Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Obsidian Flames Pokemon Center Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Paldea Evolved Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Paldea Evolved Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Scarlet & Violet Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Scarlet & Violet Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Crown Zenith Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Silver Tempest Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Silver Tempest Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Lost Origin Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Lost Origin Pokemon Center Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Astral Radiance Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Astral Radiance Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Astral Radiance Pokemon Center Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Brilliant Stars Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Brilliant Stars Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Brilliant Stars Pokemon Center Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Evolving Skies Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Chilling Reign Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Chilling Reign Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Battle Styles Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Vivid Voltage Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Darkness Ablaze Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'ETB', 'Sword & Shield Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Shining Fates Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Celebrations Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'ETB', 'Celebrations Pokemon Center Elite Trainer Box', 'EN', true, 9),
('Pokemon', 'Sealed', 'Booster Box', 'Pokemon GO Booster Box', 'EN', true, 36),
('Pokemon', 'Sealed', 'UPC', 'Phantasmal Flames UPC', 'EN', true, 18),
('Pokemon', 'Sealed', 'Collection', 'White Flare Binder Collection', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Collection', 'Black Bolt Binder Collection', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Tin', 'Unova Mini Tin', 'EN', true, 2),
('Pokemon', 'Sealed', 'Collection', 'Unova Victini Illustration Collection', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Collection', 'Unova Poster Collection', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Premium Collection', 'Prismatic Evolutions Super Premium Collection', 'EN', true, 8),
('Pokemon', 'Sealed', 'Special', 'Prismatic Evolutions Accessory Pouch Special Collection', 'EN', true, 4),
('Pokemon', 'Sealed', 'Special Box', 'Prismatic Evolutions Surprise Box', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Tin', 'Shrouded Fable Mini Tin', 'EN', true, 2),
('Pokemon', 'Sealed', 'Collection', 'Paldean Fates Tech Sticker Collection', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Ultra-Premium Collection', '151 Ultra-Premium Collection', 'EN', true, 18),
('Pokemon', 'Sealed', 'Tin', 'Costco Pokemon Scarlet & Violet 151 Mini Tin 5-pack', 'EN', true, 10),
('Pokemon', 'Sealed', 'Tin', 'Pokemon 151 Tin', 'EN', true, 4),
('Pokemon', 'Sealed', 'Collection', '151 Poster Collection', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Premium Collection', 'Pikachu VMAX Premium Collection - Crown Zenith', 'EN', true, 6),
('Pokemon', 'Sealed', 'Figure Collection', 'Crown Zenith Premium Figure Collection', 'EN', true, 6),
('Pokemon', 'Sealed', 'Ultra-Premium Collection', 'Charizard Ultra-Premium Collection', 'EN', true, 18),
('Pokemon', 'Sealed', 'Ultra-Premium Collection', 'Celebrations Ultra-Premium Collection', 'EN', true, 18),
('Pokemon', 'Sealed', 'Special', 'Celebrations Special Collection [Pikachu V]', 'EN', true, 4),
('Pokemon', 'Sealed', 'Premium Collection', 'Celebrations Premium Playmat Collection [Pikachu V]', 'EN', true, 4),
('Pokemon', 'Sealed', 'Premium Collection', 'Forces of Nature GX Premium Box', 'EN', true, 7),
('Pokemon', 'Sealed', 'Premium Collection', 'Blastoise VMAX Premium Collection', 'EN', true, 6),
('Pokemon', 'Sealed', 'Premium Collection', 'Cynthia''s Garchomp ex Premium Collection', 'EN', true, 6),
('Pokemon', 'Sealed', 'Premium Collection', 'Venusaur VMAX Premium Collection', 'EN', true, 6),
('Pokemon', 'Sealed', 'Special', 'Lucario VSTAR Special Collection', 'EN', true, 4),
('Pokemon', 'Sealed', 'Premium Collection', 'Blooming Waters Premium Collection', 'EN', true, 6),
('Pokemon', 'Sealed', 'Collection', 'Pokemon Lillie Premium Tournament Collection 4-Box', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Other', 'Pokemon TCG Holiday Calendar 2025', 'EN', false, NULL),
('Pokemon', 'Sealed', 'Special Box', 'Team Rocket''s Mewtwo ex Box', 'EN', false, NULL)
ON CONFLICT (brand, type, category, name, language) DO NOTHING;
