-- ============================================================================
-- Master Vault inventory reconcile against 5/14 physical count
-- ============================================================================
-- Generated by scripts/_build_master_reconcile_sql.mjs
-- Source: Google Sheet 5/14 master count (33 SKUs)
-- Master Vault location id: 1f68249f-7708-400c-80f7-e75bde85b556
--
-- This script is destructive. ALWAYS take a Supabase snapshot first.
-- Run inside a transaction so you can ROLLBACK if anything looks off.
-- ============================================================================

BEGIN;

-- ───────────────────────────────────────────────────────────────────────────
-- A. UPDATE inventory rows to match sheet quantities
-- ───────────────────────────────────────────────────────────────────────────
-- ✓ Mega Evo ETB PC → Mega Evolutions 1 (PC) ETB: already 2 (no change)
-- Primsatic Evo ETB → Prismatic Evolutions Elite Trainer Box: 12 → 11 (Δ -1)
UPDATE inventory SET quantity = 11, last_updated = NOW() WHERE id = '10aee763-6a55-4f80-83c6-582a3c46f2a5';
-- ✓ Ascended Heroes (packs) → Ascended Heroes Booster Pack: already 152 (no change)
-- ✓ Perfect Order (packs) → Perfect Order Booster Pack: already 120 (no change)
-- ✓ Charzard EX (UPC) → Charizard Ultra-Premium Collection: already 16 (no change)
-- ✓ Prismatic Evo SPC → Prismatic Evolutions Super Premium Collection: already 16 (no change)
-- ✓ Prismatic Tech Sticker → Prismatic tech sticker Collection: already 21 (no change)
-- ✓ Asecnded Heroes Booster Bundles → Ascended Heroes Booster Bundle: already 4 (no change)
-- First Partner Vol 1 → First Partner Illustration Collection: 30 → 10 (Δ -20)
UPDATE inventory SET quantity = 10, last_updated = NOW() WHERE id = 'b6bfb3b6-6cc3-4c8d-9838-2eb6d393737e';
-- ✓ S/V Build and Battle Stadium → Scarlet & Violet Build & Battle Stadium - SV01: Scarlet & Violet Base Set Build & Battle: already 6 (no change)
-- ✓ Perfect order build and battle box sealed → Perfect Order Build & Battle Box: already 1 (no change)
-- ✓ Forces of Nature GX Box → Forces of Nature GX Premium Box: already 1 (no change)
-- ✓ Venusaur Vmax Box → Venusaur VMAX Premium Collection: already 1 (no change)
-- ✓ PC Tohoku Special Box JP → Pokemon Center Tohoku Special Box: already 1 (no change)
-- ✓ PC Hiroshima Special Box JP → Pokemon Center Hiroshima Special Box: already 1 (no change)
-- Vivid Portrayals Indigo → Vivid Portrayals Indigo Booster Box: 24 → 12 (Δ -12)
UPDATE inventory SET quantity = 12, last_updated = NOW() WHERE id = '9e9ec0b4-dc08-4a5a-a86f-4e5052de5f90';
-- True Mystic → True Mystic Booster Box: 40 → 20 (Δ -20)
UPDATE inventory SET quantity = 20, last_updated = NOW() WHERE id = '629953f7-62de-476d-901f-b32ca0ee7c5f';
-- Chinese blastoise venusaur jumbo pack → Venusaur & Blastoise Jumbo Booster Pack: 366 → 396 (Δ 30)
UPDATE inventory SET quantity = 396, last_updated = NOW() WHERE id = '51fe8b83-0319-477b-b611-239433458984';
-- Some red Chinese promo pack → Red Promo Pack: 380 → 240 (Δ -140)
UPDATE inventory SET quantity = 240, last_updated = NOW() WHERE id = '9547e609-83cc-41f8-9fb3-43d2d5b1d183';
-- ✓ OP 13 JP → OP-13 Carrying On His Will Booster Box: already 21 (no change)
-- ✓ Promo Pack Vol 7 → vol 7 OP promo pack Booster Pack: already 100 (no change)
-- ✓ Promo Pack Vol 6 → vol 6 op promo pack Booster Pack: already 100 (no change)
-- ✓ Promo Pack Vol 4 → vol 4 promo pack Booster Pack: already 100 (no change)
-- ✓ Limit Over Collection The Rivals → Limit Over Collection The Rivals Booster Box: already 37 (no change)
-- ✓ Yu-Gi-Oh Rarity Collection Quarter Centers Edition → Rarity Collection Quarter Century Edition Booster Box: already 160 (no change)
-- ✓ Nikke → NIKKE Goddess of Victory Booster Box (Weiss Schwarz): already 99 (no change)
-- ✓ Hololive → hololive Enchant Regalia Booster Box: already 48 (no change)
-- ✓ Eminence In shadow → The Eminence in Shadow Booster Box (Weiss Schwarz): already 48 (no change)
-- EB-04 (sheet says 0) → EB-04 Memorial Collection Booster Box: 12 → 0 (Δ -12)
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = '0da41376-5500-42da-8253-5e744a4370d9';
-- EX Battle Decks (sheet plural; system singular) → EX Battle Deck: 5 → 2 (Δ -3)
UPDATE inventory SET quantity = 2, last_updated = NOW() WHERE id = 'f46dacb0-7206-41d7-ae44-6cbb9f488f4b';
-- ✓ EB 03 JP → EB-03 Heroines Edition Booster Box: already 4 (no change)

-- ───────────────────────────────────────────────────────────────────────────
-- B. ZERO out inventory rows at Master Vault NOT in the sheet
--    ("没列就是没有" — sheet is the source of truth for 5/14)
-- ───────────────────────────────────────────────────────────────────────────
-- Pokemon/EN/Sealed V Battle Deck: 2 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = '07133d21-db40-44f1-887d-53db8a71f4ef';
-- Pokemon/EN/Sealed Phantasmal Flames Build & Battle Box: 1 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = 'e1b8a715-d5b6-4de6-84c7-c8bce87fcb6b';
-- One Piece/JP/Pack 2022 promo pack Booster Pack: 8 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = '249631a6-8909-407b-8553-07147b339e8a';
-- Pokemon/CN/Sealed Gem Vol.5 Booster Box: -20 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = '8f8aebbc-e848-4f43-9de0-e4b1b4859ce1';
-- Pokemon/JP/Sealed Mystery Box Collection: 1 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = 'f127fd85-ea4f-4203-91af-57c7119096e6';
-- Pokemon/JP/Sealed PC 2019 Mewtwo Strikes Back Evolution Movie Special Box: 2 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = 'b59a0fe5-1bbf-4895-bfb9-462c46212216';
-- Pokemon/JP/Sealed S/V Starter Deck Ancient Koraidon ex: 1 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = '16297c2c-f8b7-41fe-9295-3bb23f44755c';
-- Pokemon/JP/Sealed S/V Starter Deck Generations: 2 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = 'dabc4bb8-727e-4fb8-8283-79c798d01f71';
-- Pokemon/JP/Sealed Raihan Trainer Card Collection: 1 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = '200b9edb-ea28-400f-b0c4-c063a02654eb';
-- Pokemon/JP/Sealed PoGo Special Set: 1 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = 'ad5f7de8-9514-4e9c-a907-5052a8f73ad8';
-- Pokemon/CN/Sealed Black Crystal Blaze Jumbo Booster Box: 36 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = '331493a6-bf46-4013-93bc-333350f2281a';
-- Other/CN/Sealed Big Into Energy Blind Box (Labubu): 12 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = '52f2adda-4077-4f8f-a58f-8a3e0991203a';
-- Other/EN/Sealed FB09 Dual Evolution Booster Box (Dragon Ball): 2 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = '6b20aa52-0be6-4046-940f-afb4ec56e520';
-- Pokemon/CN/Pack Blue Promo Pack: 72 → 0
UPDATE inventory SET quantity = 0, last_updated = NOW() WHERE id = 'a95d7c04-48fd-4e4a-a542-0246a0397caf';

-- ───────────────────────────────────────────────────────────────────────────
-- C. NEW PRODUCTS — sheet listed these, system has no matching product.
--    The INSERTs below create the product + give it master inventory.
--    Review each one — change brand/category/type if these defaults are wrong.
-- ───────────────────────────────────────────────────────────────────────────
-- "Promo Pack Vol 8 (One Piece)" — qty 90
WITH new_p AS (
  INSERT INTO products (name, brand, language, type, category, active)
  VALUES ('Promo Pack Vol 8 (One Piece)', 'One Piece', 'JP', 'Pack', 'One Piece', true)
  RETURNING id
)
INSERT INTO inventory (product_id, location_id, quantity)
SELECT id, '1f68249f-7708-400c-80f7-e75bde85b556', 90 FROM new_p;

-- ───────────────────────────────────────────────────────────────────────────
-- VERIFY before COMMIT:
--   SELECT p.brand, p.language, p.name, i.quantity
--   FROM inventory i JOIN products p ON p.id = i.product_id
--   WHERE i.location_id = '1f68249f-7708-400c-80f7-e75bde85b556' AND i.quantity > 0
--   ORDER BY p.brand, p.name;
--
-- If totals look right (should be 33 non-zero rows ≈ matching sheet), COMMIT.
-- Otherwise: ROLLBACK;
-- ───────────────────────────────────────────────────────────────────────────

-- COMMIT;        -- ← uncomment after verifying
-- ROLLBACK;      -- ← if anything looks off