-- ============================================================================
-- Singles reconcile — 2026-05-18
-- ============================================================================
-- Sheet source: scripts/_singles_latest_2026_05_18.csv
-- Generated by: scripts/_build_singles_reconcile_2026_05_18.mjs
--
-- Counts: 118 insert · 27 update · 177 soft-delete · 80 no-change
--
-- Safety: wrapped in BEGIN/COMMIT. Review the report file first:
--   scripts/_singles_reconcile_2026_05_18_report.md
-- ============================================================================

BEGIN;

-- A. Auto-create any missing card_sets
INSERT INTO card_sets (brand, language, name) VALUES
  ('Pokemon', 'EN', 'Aquapolis'),
  ('Pokemon', 'EN', 'Ascended Heroes'),
  ('Pokemon', 'EN', 'Astral Radiance'),
  ('Pokemon', 'EN', 'Battle Styles'),
  ('Pokemon', 'EN', 'Black Bolt'),
  ('Pokemon', 'EN', 'Celebrations'),
  ('Pokemon', 'EN', 'Chilling Reign'),
  ('Pokemon', 'EN', 'Classic Collection'),
  ('Pokemon', 'EN', 'Crimson Invasion'),
  ('Pokemon', 'EN', 'Darkness Ablaze'),
  ('Pokemon', 'EN', 'Destined Rivals'),
  ('Pokemon', 'EN', 'Evolutions'),
  ('Pokemon', 'EN', 'Evolving Skies'),
  ('Pokemon', 'EN', 'Fusion Strike'),
  ('Pokemon', 'EN', 'Gym Challenge'),
  ('Pokemon', 'EN', 'Journey Together'),
  ('Pokemon', 'EN', 'Lost Origin'),
  ('Pokemon', 'EN', 'Lost Origin Trainer Gallery'),
  ('Pokemon', 'EN', 'ME01: Mega Evolution'),
  ('Pokemon', 'EN', 'ME02: Phantasmal Flames'),
  ('Pokemon', 'EN', 'ME03: Perfect Order'),
  ('Pokemon', 'EN', 'Mega Evolution'),
  ('Pokemon', 'EN', 'Mega Evolution Promo'),
  ('Pokemon', 'EN', 'Paldea Evolved'),
  ('Pokemon', 'EN', 'Paldean Fates'),
  ('Pokemon', 'EN', 'Paradox Rift'),
  ('Pokemon', 'EN', 'Perfect Order'),
  ('Pokemon', 'EN', 'Phantasmal Flames'),
  ('Pokemon', 'EN', 'Prismatic Evolutions'),
  ('Pokemon', 'EN', 'SM - Cosmic Eclipse'),
  ('Pokemon', 'EN', 'SM - Forbidden Light'),
  ('Pokemon', 'EN', 'SM Base Set'),
  ('Pokemon', 'EN', 'SV: Black Bolt'),
  ('Pokemon', 'EN', 'SV: Paldean Fates'),
  ('Pokemon', 'EN', 'SV: Prismatic Evolutions'),
  ('Pokemon', 'EN', 'SV: Scarlet & Violet 151'),
  ('Pokemon', 'EN', 'SV: Scarlet & Violet Promo Cards'),
  ('Pokemon', 'EN', 'SV: Shrouded Fable'),
  ('Pokemon', 'EN', 'SWSH: Crown Zenith: Galarian Gallery'),
  ('Pokemon', 'EN', 'SWSH: Sword & Shield Promo Cards'),
  ('Pokemon', 'EN', 'Scarlet & Violet Base Set'),
  ('Pokemon', 'EN', 'Scarlet & Violet Promo Cards'),
  ('Pokemon', 'EN', 'Shining Fates'),
  ('Pokemon', 'EN', 'Shining Fates: Shiny Vault'),
  ('Pokemon', 'EN', 'Shrouded Fable'),
  ('Pokemon', 'EN', 'Silver Tempest Trainer Gallery'),
  ('Pokemon', 'EN', 'Stellar Crown'),
  ('Pokemon', 'EN', 'Surging Sparks'),
  ('Pokemon', 'EN', 'Sword & Shield Base Set'),
  ('Pokemon', 'EN', 'Sword & Shield Promo Cards'),
  ('Pokemon', 'EN', 'Temporal Forces'),
  ('Pokemon', 'EN', 'Twilight Masquerade'),
  ('Pokemon', 'EN', 'Unsorted / Promo'),
  ('Pokemon', 'EN', 'White Flare'),
  ('Pokemon', 'EN', 'XY - Primal Clash'),
  ('Pokemon', 'EN', 'XY Promos')
ON CONFLICT (brand, language, name) DO NOTHING;

-- B. INSERT 118 new cards from sheet
INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'M Aerodactyl EX XY98 Promo PR',
  '',
  NULL,
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '114008', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'XY Promos'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'M Slowbro EX XY UR EVO',
  '',
  NULL,
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '124040', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Evolutions'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Lunala GX',
  '66/149',
  'UR SM01',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '126937', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SM Base Set'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Alolan Exeggutor GX (Full Art) SM UR SM04',
  '',
  NULL,
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '149138', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Crimson Invasion'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Bonnie',
  '128/131',
  'FA SM06',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '165766', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SM - Forbidden Light'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Torkoal',
  '237/236',
  'Rainbow SM12',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '201348', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SM - Cosmic Eclipse'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Gallade',
  '244/236',
  'Rainbow SM12',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '201355', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SM - Cosmic Eclipse'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Frosmoth',
  'SWSH007',
  'SWSD',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '208262', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Sword & Shield Promo Cards'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Dhelmise V (Full Art)',
  '187/202',
  'UR SWSH01',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '208385', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Sword & Shield Base Set'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Team Yell Grunt (Secret)',
  '210/202',
  'Rainbow SWSH01',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '208519', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Sword & Shield Base Set'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Vikavolt V',
  '180/189',
  'FA DAA',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '219301', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Darkness Ablaze'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Salamence VMAX',
  '194/189',
  'Rainbow DAA',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '219320', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Darkness Ablaze'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Dhelmise VMAX',
  '010/072',
  'UR SHF',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '232380', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Shining Fates'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Cufant',
  'SV090/SV122',
  'SHFSV',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '232474', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Shining Fates: Shiny Vault'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Cramorant V',
  'SWSH086',
  'Promo SWSD',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '232503', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SWSH: Sword & Shield Promo Cards'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Poke Kid (Full Art)',
  '070/072',
  'UR SHF',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '232531', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Shining Fates'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Rapid Strike Style Mustard (Secret)',
  '176/163',
  'Rainbow SWSH05',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '234100', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Battle Styles'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Single Strike Energy (Secret)',
  '183/163',
  'Rainbow SWSH05',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '234109', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Battle Styles'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Rugged Helmet (Secret)',
  '228/198',
  'Rainbow SWSH06',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '241860', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Chilling Reign'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Lycanroc VMAX',
  '213/203',
  'Rainbow EVS',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '246714', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Evolving Skies'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Mew',
  '011/025',
  'Holo Rare CLB',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 6, '250309', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Celebrations'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Rocket''s Zapdos',
  '15/132',
  'Classic Collection CCC',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '250324', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Classic Collection'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Tsareena V (Full Art)',
  '246/264',
  'UR SWSH08',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '253139', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Fusion Strike'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Boltund V (Full Art)',
  '249/264',
  'UR SWSH08',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 2, '253144', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Fusion Strike'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Shauna (Full Art)',
  '263/264',
  'UR SWSH08',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 2, '253165', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Fusion Strike'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Flaaffy (Secret)',
  '280/264',
  'Rainbow SWSH08',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '253284', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Fusion Strike'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Power Tablet (Secret)',
  '281/264',
  'Rainbow SWSH08',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 2, '253285', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Fusion Strike'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Training Court (Secret)',
  '282/264',
  'Rainbow SWSH08',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '253286', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Fusion Strike'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Blanche',
  'SWSH227',
  'Promo SWSD',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '270721', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SWSH: Sword & Shield Promo Cards'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Gardenia''s Vigor (Full Art)',
  '184/189',
  'UR SWSH10',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '272434', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Astral Radiance'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Choice Belt (Secret)',
  '211/189',
  'Rainbow SWSH10',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '272466', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Astral Radiance'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Temple of Sinnoh (Secret)',
  '214/189',
  'Rainbow SWSH10',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '272469', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Astral Radiance'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Rotom V',
  '177/196',
  'Alt Art LOR',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '284119', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Lost Origin'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Hisuian Arcanine',
  'TG08/TG30',
  'UR SWSH11: TG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '284268', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Lost Origin Trainer Gallery'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Orbeetle V',
  'TG12/TG30',
  'UR SWSH11: TG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '284272', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Lost Origin Trainer Gallery'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Eternatus V',
  'TG21/TG30',
  'UR SWSH11: TG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '284294', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Lost Origin Trainer Gallery'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Opal',
  'TG28/TG30',
  'UR SWSH11: TG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '284301', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Lost Origin Trainer Gallery'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Jynx',
  'TG04/TG30',
  'UR SWSH12: TG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '452018', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Silver Tempest Trainer Gallery'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Rockruff -',
  'SWSH12',
  ': Silver Tempest Trainer Gallery (SWSH12: TG) TG07/TG30',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '452021', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Unsorted / Promo'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Zamazenta V (Shiny)',
  'SWSH293',
  'SWSD',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '477064', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Sword & Shield Promo Cards'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Hoopa V - SWSH: Crown Zenith: Galarian Gallery (CRZ:GG)',
  'GG53/GG70',
  NULL,
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '477181', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Unsorted / Promo'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Electivire - SWSH: Crown Zenith: Galarian Gallery (CRZ:GG)',
  'GG08/GG70',
  NULL,
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '478025', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Unsorted / Promo'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Miltank',
  'GG24/GG70',
  'UR CRZ:GG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '478043', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SWSH: Crown Zenith: Galarian Gallery'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Riolu - SWSH: Crown Zenith: Galarian Gallery (CRZ:GG)',
  'GG26/GG70',
  'CRZ:GG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 2, '478045', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Unsorted / Promo'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Dondozo',
  '207/198',
  'IR SVI',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '487060', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Scarlet & Violet Base Set'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Armarouge',
  '203/198',
  'IR SVI',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '490063', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Scarlet & Violet Base Set'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Penny',
  '239/198',
  'UR SVI',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 2, '490097', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Scarlet & Violet Base Set'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Great Tusk ex',
  '246/198',
  'SIR SVI',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '490290', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Scarlet & Violet Base Set'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Miraidon',
  '013',
  'SVP',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '490719', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Scarlet & Violet Promo Cards'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Quaxwell',
  '207/193',
  'IR PAL',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '497610', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Paldea Evolved'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Flamigo',
  '227/193',
  'IR PAL',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 2, '497630', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Paldea Evolved'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Wo-Chien ex',
  '232/193',
  'UR PAL',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '497637', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Paldea Evolved'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Grusha',
  '268/193',
  'SIR PAL',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '497688', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Paldea Evolved'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Arbok ex',
  '185/165',
  'UR MEW',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '517014', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Scarlet & Violet 151'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Bill''s Transfer',
  '194/165',
  'UR MEW',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '517041', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Scarlet & Violet 151'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Switch',
  '206/165',
  'HR MEW',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '517052', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Scarlet & Violet 151'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Espathra',
  '197/182',
  'IR PAR',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '523878', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Paradox Rift'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Garbodor',
  '204/182',
  'IR PAR',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '523885', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Paradox Rift'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Yveltal',
  '205/182',
  'IR PAR',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '523886', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Paradox Rift'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Loudred',
  '212/182',
  'IR PAR',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '523893', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Paradox Rift'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Swablu',
  '213/182',
  'IR PAR',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '523894', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Paradox Rift'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Sandy Shocks ex',
  '228/182',
  'UR PAR',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '523909', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Paradox Rift'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Scyther',
  '095/091',
  'Shiny PAF',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '534463', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Paldean Fates'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Ralts',
  '153/091',
  'Shiny PAF',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '534650', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Paldean Fates'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Pidgeotto',
  '197/091',
  'Shiny PAF',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '535165', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Paldean Fates'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Snom',
  '168/162',
  'IR TEF',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '542889', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Temporal Forces'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Relicanth',
  '173/162',
  'IR TEF',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '542894', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Temporal Forces'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Eri',
  '199/162',
  'UR TEF',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '542920', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Temporal Forces'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Bianca''s Devotion',
  '209/162',
  'SIR TEF',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '542930', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Temporal Forces'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Salvatore',
  '212/162',
  'SIR TEF',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '542933', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Temporal Forces'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Lairon',
  '184/167',
  'IR TWM',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '550228', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Twilight Masquerade'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Lucian',
  '208/167',
  'UR TWM',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '550252', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Twilight Masquerade'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Teal Mask Ogerpon',
  '123',
  'Promo SVP',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 2, '552785', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Scarlet & Violet Promo Cards'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Munkidori ex',
  '083/064',
  'UR SFA',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '560394', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Shrouded Fable'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Pecharunt ex',
  '085/064',
  'UR SFA',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '560396', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Shrouded Fable'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Munkidori ex',
  '091/064',
  'SIR SFA',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '560402', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Shrouded Fable'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Crabominable',
  '149/142',
  'IR SCR',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '567431', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Stellar Crown'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Meditite',
  '153/142',
  'IR SCR',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '567436', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Stellar Crown'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Galvantula ex',
  '168/142',
  'SIR SCR',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '567474', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Stellar Crown'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Noctowl',
  '141',
  '(Pokemon Center Exclusive) Promo SVP',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '578812', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Scarlet & Violet Promo Cards'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Drayton',
  '244/191',
  'SIR SSP',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '589925', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Surging Sparks'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Kecleon',
  '213/191',
  'IR SSP',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '589975', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Surging Sparks'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Mesprit',
  '204/191',
  'IR SSP',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '590003', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Surging Sparks'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Counter Gain',
  '249/191',
  'HR SSP',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '593856', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Surging Sparks'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Brassius',
  '135/131',
  'UR PRE',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '610490', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Prismatic Evolutions'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Giacomo',
  '138/131',
  'UR PRE',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '610493', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Prismatic Evolutions'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Iron Leaves ex',
  '176/131',
  'HR PRE',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 2, '610531', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Prismatic Evolutions'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Teal Mask Ogerpon ex',
  '177/131',
  'HR PRE',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '610532', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Prismatic Evolutions'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Hippopotas (Master Ball Pattern)',
  '052/131',
  'PRE',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '610674', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Prismatic Evolutions'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Lillie''s Ribombee',
  '183',
  'SVP',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '623235', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Scarlet & Violet Promo Cards'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Swinub',
  '165/159',
  'IR JTG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '623592', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Journey Together'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Cynthia''s Garchomp ex',
  '215/182',
  'UR DRI',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '633015', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Destined Rivals'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Team Rocket''s Giovanni',
  '225/182',
  'UR DRI',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '633025', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Destined Rivals'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Cofagrigus',
  '123/086',
  'IR WHT',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '642235', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'White Flare'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Simipour',
  '102/086',
  'IR BLK',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '642555', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Black Bolt'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Beheeyem',
  '121/086',
  'IR BLK',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '642576', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Black Bolt'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Pawniard',
  '142/086',
  'IR BLK',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '642596', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Black Bolt'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Bisharp',
  '143/086',
  'IR BLK',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '642597', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Black Bolt'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Reuniclus (Master Ball Pattern)',
  '039/086',
  'BLK',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '642662', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Black Bolt'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Tornadus',
  '210',
  'Promo SVP',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '644835', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'SV: Scarlet & Violet Promo Cards'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Houndstone',
  '145/132',
  'IR MEG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '654484', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'ME01: Mega Evolution'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Gumshoos',
  '153/132',
  'IR MEG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '654492', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'ME01: Mega Evolution'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Air Balloon',
  '166/132',
  'UR MEG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '654505', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'ME01: Mega Evolution'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Mega Signal',
  '171/132',
  'UR MEG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 2, '654510', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'ME01: Mega Evolution'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Mystery Garden',
  '172/132',
  'UR MEG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 2, '654511', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Mega Evolution'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Rare Candy',
  '175/132',
  'UR MEG',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '654514', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'ME01: Mega Evolution'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Ambipom',
  '107/094',
  'IR PFL',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '662128', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'ME02: Phantasmal Flames'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Blowtorch',
  '117/094',
  'UR PFL',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '662133', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'ME02: Phantasmal Flames'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Rotom ex',
  '126/094',
  'SIR PFL',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '662222', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Phantasmal Flames'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Oricorio ex',
  '024',
  'MEP',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '664010', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Mega Evolution Promo'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Scorbunny',
  '225/217',
  'IR ASC',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 2, '676037', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Ascended Heroes'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Fan Rotom',
  '250/217',
  'IR ASC',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '676062', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Ascended Heroes'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Wondrous Patch ME03 UR POR',
  '',
  NULL,
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 3, '684331', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Perfect Order'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Meowth ex',
  '062/088',
  'POR',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '684340', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'ME03: Perfect Order'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Doublade',
  '098/088',
  'IR POR',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '684380', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Perfect Order'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Koga''s Pidgeotto',
  '027/132',
  'G2',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '86515', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Gym Challenge'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Quagsire',
  '030/147',
  'AQ',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '88467', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'Aquapolis'
ON CONFLICT DO NOTHING;

INSERT INTO singles (
  card_name, card_number, variant, set_id, brand, language,
  form, condition, quantity, tcg_id, status, location_id, date_acquired
) SELECT
  'Kingdra (Alpha)',
  '108/160',
  'Holo Rare PRC',
  cs.id, 'Pokemon', 'EN',
  'raw', 'NM', 1, '96006', 'in_inventory',
  '14d5db72-84de-4e49-901e-4d8230525691'::uuid, '2026-05-18'::date
FROM card_sets cs
WHERE cs.brand = 'Pokemon' AND cs.language = 'EN' AND cs.name = 'XY - Primal Clash'
ON CONFLICT DO NOTHING;

-- C. UPDATE quantity for 27 cards where sheet ≠ DB
UPDATE singles SET quantity = 2 WHERE id = '2f7853b0-2525-49c2-89cf-d190391fe660'::uuid;
UPDATE singles SET quantity = 2 WHERE id = 'eb92dcb2-d824-4de5-ac7d-e87aa1b3d933'::uuid;
UPDATE singles SET quantity = 3 WHERE id = 'ff732e29-e78d-45d3-9a5f-f1b13a8125b5'::uuid;
UPDATE singles SET quantity = 2 WHERE id = '13f495ad-aed4-4e03-ac73-ada093bbb55a'::uuid;
UPDATE singles SET quantity = 1 WHERE id = '184ba004-e608-4f5f-a30b-e8b1a68cd846'::uuid;
UPDATE singles SET quantity = 2 WHERE id = '6299aa44-1db2-4c0f-9287-c3ff39197dbf'::uuid;
UPDATE singles SET quantity = 1 WHERE id = '13500b69-995e-4e3b-a056-8b07c599cd89'::uuid;
UPDATE singles SET quantity = 1 WHERE id = '1f6aa839-89cf-490e-b8da-08ca6303dcc1'::uuid;
UPDATE singles SET quantity = 4 WHERE id = '9d05c290-71b4-49a5-93f2-3b0d04c7e1f2'::uuid;
UPDATE singles SET quantity = 2 WHERE id = '9c6ca21f-945a-484f-9cff-b57d08a656c4'::uuid;
UPDATE singles SET quantity = 2 WHERE id = '14f472d9-3bfe-4003-9085-74cfcbd4afe9'::uuid;
UPDATE singles SET quantity = 2 WHERE id = '476f7030-7315-4523-8955-2647dccca4df'::uuid;
UPDATE singles SET quantity = 2 WHERE id = '54ad56fb-0fb0-4163-9327-68d719683990'::uuid;
UPDATE singles SET quantity = 1 WHERE id = 'a1f96ede-4735-4a17-b061-a77fe08f652c'::uuid;
UPDATE singles SET quantity = 1 WHERE id = '91a767dc-8c5f-49f2-8c3f-92f607c1589d'::uuid;
UPDATE singles SET quantity = 3 WHERE id = '5d885410-7cab-4019-89cb-6807a70d5170'::uuid;
UPDATE singles SET quantity = 2 WHERE id = '06b28d43-f4db-44cd-8777-c17771ace1ff'::uuid;
UPDATE singles SET quantity = 2 WHERE id = '52226a08-f986-478a-a13e-0914aedef303'::uuid;
UPDATE singles SET quantity = 1 WHERE id = '7ed3a8ab-2ee3-493d-beb3-b5caaeb6e40c'::uuid;
UPDATE singles SET quantity = 4 WHERE id = '7ab2bd74-4ae8-4864-adaa-c5c34d98ab37'::uuid;
UPDATE singles SET quantity = 2 WHERE id = 'ef23cea1-a29f-439f-8766-55732d1f6a0e'::uuid;
UPDATE singles SET quantity = 3 WHERE id = 'dc55ce7e-aefd-4ad0-9078-316e68afdc56'::uuid;
UPDATE singles SET quantity = 1 WHERE id = 'b3f03cd0-8c60-45f4-beda-a033597dfa24'::uuid;
UPDATE singles SET quantity = 5 WHERE id = 'e9ec9379-be60-4144-a444-234734787948'::uuid;
UPDATE singles SET quantity = 3 WHERE id = '84905dff-a25b-446e-a4bb-ca6e0c6e6fe1'::uuid;
UPDATE singles SET quantity = 3 WHERE id = '2b64ca42-63ea-40fe-a4a5-b39ec63844b7'::uuid;
UPDATE singles SET quantity = 2 WHERE id = 'f114715f-93b2-4286-ac26-3c7907ca8c54'::uuid;

-- D. Soft-delete 177 cards in DB but not in 2026-05-18 sheet
UPDATE singles
SET deleted = true,
    deleted_at = now(),
    deleted_reason = 'Not in 2026-05-18 physical count'
WHERE id IN (
  'ac56f6e5-d222-45bc-bb62-9fd674a2419d'::uuid,
  'baa52e3c-55ea-4975-a5f4-6045d7bc4a4f'::uuid,
  'bbcc9f8e-500e-4f81-8cf1-30b0ca34c534'::uuid,
  'efa91ece-1711-4b4f-8c29-cf9383dcdc40'::uuid,
  'bdd28c0b-21ff-422d-bd60-f5bc708f6973'::uuid,
  '80fb4907-7bc8-4820-9ee4-34d7e0a8facb'::uuid,
  'c1a0da39-03e4-46de-92d7-2166041cd2a1'::uuid,
  'e468a2f3-36d2-4388-9444-acad1733008c'::uuid,
  '5f24885e-ecba-4818-96f7-0112451cc492'::uuid,
  '77faad38-d2ac-44c1-9134-bce68f962420'::uuid,
  '41560672-4c3a-43fa-a110-034979226358'::uuid,
  'd91d21db-c36a-4d01-943f-0e1cbb548a96'::uuid,
  '1fd55309-1f2b-4db3-aeca-35e6466ff927'::uuid,
  'd774612f-609d-4478-ba15-61e5bcbba279'::uuid,
  'df1f6c9c-b548-4a32-8991-8080c4b41b23'::uuid,
  'ec3ef3ea-9f42-4b7d-a805-f041bc02500f'::uuid,
  '6d3d5c1b-1f9e-48de-a7f8-ccec055134e5'::uuid,
  'c49a1c8e-b6d4-4bf8-9ce0-e5371c40f3f3'::uuid,
  '7cc60e8c-7d22-4b3f-86bb-d6c85627c1f2'::uuid,
  'fc5540ab-ddec-48aa-8865-c7a2afdb2b34'::uuid,
  'c7ff8610-ba0f-45b1-a259-5035a579608a'::uuid,
  'cfbb552e-efad-4473-8dfc-307d19c751da'::uuid,
  'b561fed4-8e32-4eb9-acbd-8d3035567e61'::uuid,
  '4488be03-040d-4def-be84-6467871ea5e6'::uuid,
  'd35c0c80-e8b7-4da3-9114-0046a0c08080'::uuid,
  '6418912b-58c5-4ef1-9ff8-6af883d1c603'::uuid,
  '5f8643ce-31a7-4cf7-a86c-1c28a236142f'::uuid,
  'af959f3e-b6d5-4140-8ae5-27ad22807772'::uuid,
  'faca004b-e74e-4cd4-985e-d73f550340ed'::uuid,
  'd7e121ec-2cef-4418-aae0-8643c27bacf8'::uuid,
  '054194b5-6c85-40e0-96ab-26b1f4036e8e'::uuid,
  '558696d4-ea1c-4cb8-b3e5-9d765db24c3c'::uuid,
  'c2f90423-6c27-4f8a-a9ed-ca1b6f757557'::uuid,
  '0b45cdc9-bd2c-473e-9bff-16bd065a6e50'::uuid,
  '3a610ad3-9605-4fe6-97ef-11ab8c4067b3'::uuid,
  'f839938d-c47b-4fe1-a7ce-03e435b0dba0'::uuid,
  'a4812c4c-7656-4e8e-bfb3-b2cbc1c89a5a'::uuid,
  '71742343-b3ae-4fec-abea-fce8cdc3ae41'::uuid,
  '737ab510-3758-4c66-b128-ab7d3fac5b5a'::uuid,
  'c6faceb2-108b-43b8-9288-b94b17b73c15'::uuid,
  '08dc608f-933a-4ebe-8ca9-070701889aa0'::uuid,
  '7ce1b0c1-4b9d-4090-b86b-3102d8f7184c'::uuid,
  'b5396f15-0bee-47c5-8c77-3611a0d8b64c'::uuid,
  '0b9c2685-163b-4cf2-99f6-d5ec9f492cea'::uuid,
  '8bb5477c-42fb-4eb9-97ef-53c1c0f58d4d'::uuid,
  '2e4a5ca6-c56b-4014-bb02-2984150e1f6e'::uuid,
  '3bf80d27-fb37-48a9-b689-c36f9b832592'::uuid,
  'fc6e45b7-7b02-4ad6-88b9-1bf03b824ab8'::uuid,
  'e35ee3ff-41bc-4171-9cae-0a3118079ae6'::uuid,
  '2ea59c4b-3b34-4943-9044-2ba3adc88617'::uuid,
  'c7d1e1e1-532a-409a-9a00-4a1fdeba20b8'::uuid,
  '2e835d1b-c24b-4a69-892d-84821e6ecb48'::uuid,
  'cf0d237b-422d-424c-9e71-0d42a97754f6'::uuid,
  'e2281e97-844f-4121-8c7a-d261c9c74803'::uuid,
  '9d2f03df-8aca-4148-b362-14325b67435b'::uuid,
  'acb03fb4-619e-4cdc-a116-1200d114ecc2'::uuid,
  'c609c1ab-e857-4be6-8a58-3ffd6639fa36'::uuid,
  '43f28edc-697c-40ea-9b38-8e1465aa336b'::uuid,
  'daacb4d8-51e9-4971-886c-c3ef751b9fa6'::uuid,
  '81ff336e-0bc7-4da4-ad43-31378f1ba33f'::uuid,
  '82e065be-fc05-4b5f-87c4-4e14b66a6095'::uuid,
  '84e22abf-d636-4271-8404-2007053cc1f4'::uuid,
  'eb1feb06-5fa1-43e6-a9de-7bf8c6b4a4f3'::uuid,
  '6d84e8f7-05f9-41cf-aea7-b6fc0090a400'::uuid,
  '839d1b7e-2cca-45c6-8dcd-6418446e2864'::uuid,
  '60324a31-712a-4f2f-b113-96a42f27be2d'::uuid,
  '0fb81e02-6abe-44f1-8727-330ff55ce733'::uuid,
  '3a0c2e56-53a8-442c-95da-59022119331d'::uuid,
  '4d256c8c-f8d6-4ff9-a8ac-957b3607202e'::uuid,
  'eb44946f-3eb9-48ec-a03b-680aeff6da4c'::uuid,
  '6d226cda-5b4f-46bd-9e94-0a2f6af0d57d'::uuid,
  'cef4f53a-393e-4aea-81b7-1f2027686ac8'::uuid,
  'fce3229d-31d6-4e3a-8875-7e5c6a9d2946'::uuid,
  'c03120d7-8cb8-4675-bb68-8721511856e3'::uuid,
  'bf24b0b0-4a86-413e-8395-f700744a84c6'::uuid,
  '58d4e32e-62e5-4d63-9f5c-73a502839927'::uuid,
  '73033a1c-82f1-4f9e-b50d-7efbe82d49cb'::uuid,
  '6408f619-5b78-4952-ad22-8a5fc0745791'::uuid,
  'b4c07e95-c75d-422c-9d2d-7e5543bb403a'::uuid,
  '6b4725b3-98b2-4792-9acb-e8a872fe76ac'::uuid,
  '51a7dfa9-650d-4348-a271-6fdf25153495'::uuid,
  'e832170d-8aca-4a83-a5c7-e044c04d60f5'::uuid,
  'bcbc97b3-efc9-48c3-a08b-3c1cf2d3560e'::uuid,
  '0c275682-8f8a-42a6-afa6-751a9e79c9e9'::uuid,
  '85d61148-be6d-4444-9a7a-427b94f9abfc'::uuid,
  'd9a70453-25c1-4f9a-8940-8e2ceec258f7'::uuid,
  'dc29649a-3c0a-4d5d-a028-e72f1205ffe4'::uuid,
  'a9790a27-b4ad-46c1-b336-800b2b7c0652'::uuid,
  '63fac8c7-bbe0-4b89-b6d4-ff565a8fd4f2'::uuid,
  'f87a7f57-0135-40a7-98e9-811338c4345a'::uuid,
  'cf7268de-9d04-4a96-bc03-989cebf4bffb'::uuid,
  '1e1e3581-45b0-4e15-a297-8fa250f4d2ef'::uuid,
  'a346871c-cee8-4892-bd3c-58265d7a7896'::uuid,
  'cd0b7bd0-28d1-4273-abf8-117d024b4635'::uuid,
  '50d79467-7874-4965-ac4b-0c8b8698da8b'::uuid,
  '5d4c4d8b-0a8c-4191-a5f5-f72e613d85d0'::uuid,
  'adee30c6-2042-4d5d-a760-c42ed239243c'::uuid,
  'd2979b26-31cc-4437-bf61-335815daad07'::uuid,
  '1ec9ad0f-0bca-4d4a-892b-7d38bab0eebb'::uuid,
  'bc303a17-f970-4e91-86ac-85e9087649d0'::uuid,
  '9e23011b-5a1d-4959-84ac-fd9b4fc0cf01'::uuid,
  '02daebb9-fc84-42de-a782-a2025da23cc4'::uuid,
  'a2e16057-d9e1-436a-8cf2-f11f7c9b7f41'::uuid,
  'c6be4270-97bf-4142-a12a-8dd8483e8c8a'::uuid,
  '6685f839-e47e-471f-bcf0-7f9dbbfc95a0'::uuid,
  '1b886f6d-a834-4ef3-bacd-71a6f8e2416b'::uuid,
  'd00f084c-5808-40f6-9df6-375d82501504'::uuid,
  'f682037d-848f-412d-9078-fc7fe67f2fda'::uuid,
  'f468ab3a-d70c-4195-98f1-ad9f53d02b4a'::uuid,
  'a8e6a828-7b60-4b7c-ab61-9951c2a5cd19'::uuid,
  'cffef934-578e-4416-bdf4-0b3963b53c86'::uuid,
  'ba530f52-5f06-4fe3-9853-49e1ca7bba49'::uuid,
  '0a190658-28e7-4838-bec9-8cb740b543b4'::uuid,
  '947b8d78-b994-44f4-b85b-9d62ee075087'::uuid,
  '2f73bb59-fc98-4eb1-96bb-a3ed60a03776'::uuid,
  'f745cb4e-2ff4-47c2-b5fb-f1c76cff6a13'::uuid,
  '357e1029-3819-4952-bdc5-66660df6bcf1'::uuid,
  '7de11c21-568f-40bf-9f53-a530a0335a00'::uuid,
  '7484c12d-18d2-4577-befb-8b084536c6ba'::uuid,
  'f29e6343-e98f-4b96-8bd2-b37625fd95e7'::uuid,
  '2378a82d-3968-4e8d-9a35-6ac3d090910f'::uuid,
  'c8d819f8-cdde-448b-93bf-a7e83c876019'::uuid,
  '1aa34083-5f97-4bef-9e27-7690d3ae998b'::uuid,
  '4680c354-d388-42b7-82d0-1f3e56bbdacd'::uuid,
  'b9f8c812-7b39-471b-99de-79fedeb6977e'::uuid,
  '7c3c31ee-a329-4784-8d14-0e30912cfe15'::uuid,
  '2a978742-0e69-47ab-ab4a-04263f327843'::uuid,
  '965d2f9e-f959-4f96-9702-93621c932899'::uuid,
  'db5aafe2-8025-4770-9ab2-4ac6032d8aca'::uuid,
  'f06595d9-04f4-452e-a395-013fba0a5e57'::uuid,
  '582c33d3-d738-4c2c-b126-09b8fa613840'::uuid,
  'd9c8ae86-eaeb-43bf-bf5a-9bc21df58d12'::uuid,
  '08279ab8-5e04-4605-afce-855adc9870ba'::uuid,
  '9e098d70-73d1-4b2e-97f6-c2711cd33236'::uuid,
  'b6d5bdcf-de96-4ca8-b3e7-2823c2387bc4'::uuid,
  'bcdd8538-9b0a-4dcc-920d-9862da3c86a5'::uuid,
  '5113df53-62eb-4558-bdd6-bbfa62fc12fd'::uuid,
  '0904d154-384c-4521-91cb-f277882a83fa'::uuid,
  '3dc0ac9d-8dad-4f8c-b575-f9cdae14aca5'::uuid,
  'f1d4b2db-4062-4c08-9011-6321ac5c13ec'::uuid,
  '94b7cd6e-7916-4d19-aa49-cbacf16745b5'::uuid,
  'a34bb3a9-a27c-4d78-b546-c7e7eb052b17'::uuid,
  '60157a3b-99d0-451a-97a0-cf13bbc2724a'::uuid,
  '1500a830-8a2d-4168-bd90-e0719142575b'::uuid,
  '61ba9b53-acde-45ae-9c0c-3ebaba0d08c9'::uuid,
  '038fdab6-ce00-41a4-be89-ec193799fa8b'::uuid,
  'e1e7e784-fb1d-46f3-b989-f5da980ca81f'::uuid,
  '6d9d396c-c1f4-425c-b95b-615c42ee2056'::uuid,
  '8698be7a-67df-4ef6-b401-e27b35b58ac8'::uuid,
  '146a33ac-80a4-42f1-8b1f-c23a3f698a34'::uuid,
  '6261f574-f091-4b7d-8a31-f2d6bfd47994'::uuid,
  '16492728-4d2c-44cc-b98e-88ed213df065'::uuid,
  '6cf7d381-f40d-41df-941f-3567d5324344'::uuid,
  '657b6911-1d0d-408d-becc-48280db0e35c'::uuid,
  '34928b65-509d-418a-b287-a881cddedfcb'::uuid,
  '53213409-fc24-444b-b9fd-6c070bdef879'::uuid,
  '70eec87c-96e4-4e5d-a926-1da59354fda5'::uuid,
  '1018b0b9-3875-4c80-abef-c564cde21766'::uuid,
  '4d78d48b-00b5-498d-b413-d9938e1a126d'::uuid,
  '3907d968-c868-46db-b008-b7b477f037b8'::uuid,
  '27bd3e49-7695-472a-8dcf-c707256a4777'::uuid,
  'a3b33989-b98e-4a99-b8e1-aed28be2e484'::uuid,
  '01ca55f4-7ae1-4083-b4c5-047f48745a77'::uuid,
  '79379746-43ac-4afc-9a86-d1d6b74a352d'::uuid,
  'fd4f1366-e9cc-4156-a669-e4e3634b7d3c'::uuid,
  '32286b7e-2b60-4d35-b2fc-3eecbe08ba19'::uuid,
  'f52472ba-766c-4e9a-bb1c-3d30d116f8a3'::uuid,
  '1b8f7f7d-be7b-4cae-a4bb-e6e9dde037ea'::uuid,
  '6ee42896-f3d5-468d-bae4-2918b707a545'::uuid,
  '1da87464-df3d-4693-ac12-2c166b942892'::uuid,
  'e115a42a-37eb-4220-a13b-a79807a66f83'::uuid,
  '2cfe4fde-be1e-4e00-b5a0-39113f9203b5'::uuid,
  '206be014-31ab-4322-af64-bbbbcd098ef0'::uuid,
  '1ae38de0-b4c4-45c0-bf89-265c034d5634'::uuid,
  '7414e6d9-f1d0-4b6d-8fcc-f73d1f112a3c'::uuid,
  'b9ca8ea5-2f4d-43ca-9093-e83ad165c501'::uuid,
  'd88334f3-c9e9-4869-9fce-1ea0806b4b85'::uuid
);

COMMIT;

-- Verify
SELECT
  COUNT(*) FILTER (WHERE deleted IS NULL OR deleted = false) AS active_total,
  COUNT(*) FILTER (WHERE deleted = true AND deleted_reason = 'Not in 2026-05-18 physical count') AS soft_deleted_today
FROM singles WHERE form = 'raw';